1 iniital implementation
EmersonElectricCo/lowball-ad-auth-provider pull request #2
Opened 2021-06-23 13:40 UTC by ieichen137

first whack at initial implementation.

2021-07-07 03:01 UTC, compsecmonkey requested changes
Looks good minus some minor suggestions. Lets circle back on the changes and tomorrow im going to download into a new environment and test

2021-07-07 03:01 UTC, compsecmonkey commented on README.md
> +The configuration for the ad auth provider goes under the `auth_provider` section of a lowball configuration
Suggest we move this line to be the intro line of configuration in general (line 32)

2021-07-07 03:01 UTC, compsecmonkey commented on README.md
> +    return {"hello": "good byte"}, 200
```suggestion

```

im not sure this is really necessary for the example. If we are to include it, i would recommend we make it a protected route otherwise could cause confusion.

2021-07-07 03:01 UTC, compsecmonkey commented on docs/contents.rst
> +
```suggestion

The configuration for the ad auth provider goes under the `auth_provider` section of a lowball configuration

```

2021-07-07 03:01 UTC, compsecmonkey commented on docs/contents.rst
> +        return {"hello": "good byte"}, 200
```suggestion
   
```

same as the readme suggest we just drop this part of the example

2021-07-07 03:01 UTC, compsecmonkey commented on lowball_ad_auth_provider/auth_provider.py
> +                conn.unbind()
```suggestion
                conn.unbind()
                
                user_groups = user_data['entries'][0]['attributes']['memberOf']
                roles = self.get_roles(user_groups)
                
```

Suggest we go ahead and unbind right away; no point in keeping open and possibly leaving it orphaned if we have run into errors w/ post-processing.

2021-07-07 03:01 UTC, compsecmonkey commented on lowball_ad_auth_provider/auth_provider.py
> +                    conn.unbind()
```suggestion
                    conn.unbind()
                    user_groups = user_data['entries'][0]['attributes']['memberOf']
                    roles = self.get_roles(user_groups)

```
Same suggestion as before

2021-07-07 03:01 UTC, compsecmonkey commented on lowball_ad_auth_provider/auth_provider.py
> +                    conn.unbind()
In general, i wonder if it makes since for the round to combine all of this into a single function either of the flow calls. From what i can tell its "all the same code" If i'm missing something and it its more complex than just breaking into a function and calling then i think we make an issue to refactor and come back to it.

2021-07-07 03:01 UTC, compsecmonkey commented on setup.py
> +      author="Timothy Lemm",
```suggestion
      author="Isaiah Eichen, Timothy Lemm",
```

2021-07-07 14:26 UTC, compsecmonkey commented
I was able to pull down this morning and run the test docker image successfully. I dont have access to a AD server right now to test so assuming a functions test was done as part of development. Once we resolve the suggestions i think were good to merge.

2021-07-08 03:06 UTC, ieichen137 commented on lowball_ad_auth_provider/auth_provider.py
> +                    conn.unbind()
ill see if I can come up with a function solution that makes sense for both flows.

the only real changes are who is authenticating, the user or the service account, and error messages

2021-07-08 03:29 UTC, ieichen137 commented on lowball_ad_auth_provider/auth_provider.py
> +                    conn.unbind()
but honestly that's actually most of what's happening. it's like 5 lines of actual code and the rest is just multiline function calls. 

we could make some kind of function for the search specifically I suppose, with the connection.

2021-07-08 03:41 UTC, ieichen137 commented on lowball_ad_auth_provider/auth_provider.py
> +                    conn.unbind()
check out the changes

2021-07-08 14:30 UTC, compsecmonkey approved these changes
I think were good to go

2021-07-08 14:35 UTC, merged